# This is loaded on startup of temp_manager
# Change the params thru the API when temp_manager is running.
# API updates will also update this file
fan_retain: 90.0
high: 21.5
low: 21.0
tick_time: 5.0